/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Answers', [
      // 1
      {
        title: 'Конструкция, что выполняет код несколько раз',
        question_id: 1,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Конструкция для создания определенной переменной',
        question_id: 1,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Оператор сравнения значений',
        question_id: 1,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 2
      {
        title: 'var num = "STRING"',
        question_id: 2,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var isDone = 0',
        question_id: 2,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var b = false',
        question_id: 2,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var number = 12,5',
        question_id: 2,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 3
      {
        title: 'Только числа и строки',
        question_id: 3,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Строки, числа с точкой и простые числа',
        question_id: 3,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Строки, числа с точкой, простые числа и булевые выражения',
        question_id: 3,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 4
      {
        title: 'Веб-приложения',
        question_id: 4,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Прикладное программное обеспечение',
        question_id: 4,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Мобильные приложения',
        question_id: 4,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Можно во всех перечисленных',
        question_id: 4,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 5
      {
        title: 'Они ничем не отличаются',
        question_id: 5,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'confirm вызывает диалоговое окно с полем для ввода, prompt - окно с подтверждением',
        question_id: 5,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'prompt вызывает диалоговое окно с полем для ввода, confirm - окно с подтверждением',
        question_id: 5,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // 6
      {
        title: '"Yes"',
        question_id: 6,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'a',
        question_id: 6,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '5',
        question_id: 6,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '"No" ',
        question_id: 6,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 7
      {
        title: 'Они ничем не отличаются',
        question_id: 7,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'confirm вызывает диалоговое окно с полем для ввода, prompt - окно с подтверждением',
        question_id: 7,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'prompt вызывает диалоговое окно с полем для ввода, confirm - окно с подтверждением',
        question_id: 7,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // 8
      {
        title: 'Число 10',
        question_id: 8,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Значение пустой строки',
        question_id: 8,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Значение undefined',
        question_id: 8,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Значение Nan',
        question_id: 8,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 9
      {
        title: 'var 2num',
        question_id: 9,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var num',
        question_id: 9,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var num-1',
        question_id: 9,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var num_1',
        question_id: 9,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 10
      {
        title: 'for, forMap, foreach, while',
        question_id: 10,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'for, while, do while',
        question_id: 10,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'for, forMap, foreach, while, do while',
        question_id: 10,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'for, while, do while, foreach',
        question_id: 10,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 11
      {
        title: 'Выполняет работу с сервером',
        question_id: 11,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Создает разметку на странице сайта',
        question_id: 11,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Отвечает за работу с базами данных',
        question_id: 11,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Отвечает за функции на стороне клиента',
        question_id: 11,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 12
      {
        title: 'new alert ("Hi")',
        question_id: 12,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'info ("Hi")',
        question_id: 12,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Нет верных вариантов',
        question_id: 12,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'alert ("Hi")',
        question_id: 12,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 13
      {
        title: 'Необходима точка с запятой после console.log("Hi!")',
        question_id: 13,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Запись console.log необходимо прописывать лишь в отдельных файлах',
        question_id: 13,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Неверно записан атрибут type',
        question_id: 13,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // 14
      {
        title: 'documentWrite("Hello")',
        question_id: 14,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'print(Hello)',
        question_id: 14,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'write("Hello")',
        question_id: 14,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'console.log("Hello")',
        question_id: 14,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 15
      {
        title: '5',
        question_id: 15,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Такой цикл работать не будет',
        question_id: 15,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '15',
        question_id: 15,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '25',
        question_id: 15,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // middle

      // 16
      {
        title: '',
        question_id: 16,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 16,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 16,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 16,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 17
      {
        title: '',
        question_id: 17,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 17,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 17,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 17,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 18
      {
        title: '',
        question_id: 18,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 18,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 18,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 18,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 19
      {
        title: '',
        question_id: 19,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 19,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 19,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 19,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 20
      {
        title: '',
        question_id: 20,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 20,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 20,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 20,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 21
      {
        title: '',
        question_id: 21,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 21,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 21,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 21,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 22
      {
        title: '',
        question_id: 22,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 22,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 22,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 22,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 23
      {
        title: '',
        question_id: 23,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 23,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 23,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 23,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 24
      {
        title: '',
        question_id: 24,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 24,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 24,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 24,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 25
      {
        title: '',
        question_id: 25,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 25,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 25,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 25,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 26
      {
        title: '',
        question_id: 26,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 26,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 26,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 26,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 27
      {
        title: '',
        question_id: 27,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 27,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 27,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 27,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 28
      {
        title: '',
        question_id: 28,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 28,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 28,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 28,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 29
      {
        title: '',
        question_id: 29,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 29,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 29,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 29,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 30
      {
        title: '',
        question_id: 30,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 30,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 30,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '',
        question_id: 30,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // senior

      // 31
      {
        title: 'На объект, в контексте которого вызван метод.',
        question_id: 31,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'На объект, переданный качестве первого параметра метода.',
        question_id: 31,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'На объект, внутри которого создан метод.',
        question_id: 31,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // 32
      {
        title: 'В произвольном порядке (определяется браузером).',
        question_id: 32,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'В том же порядке в каком были назначены.',
        question_id: 32,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'В обратном порядке.',
        question_id: 32,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // 33
      {
        title: '1 января 2015 00:00',
        question_id: 33,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Нет правильного варианта.',
        question_id: 33,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '31 декабря 2014 00:00',
        question_id: 33,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '30 декабря 2014 00:00',
        question_id: 33,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 34
      {
        title: 'push',
        question_id: 34,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'unshift',
        question_id: 34,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'shift',
        question_id: 34,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'substring',
        question_id: 34,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 35
      {
        title: 'С помощью специального метода Date.parse(<строка>). +',
        question_id: 35,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Нужно передать дату в виде строки при создании объекта с помощью new',
        question_id: 35,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Date(<строка>).',
        question_id: 35,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Можно как использовать метод Date.parse(<строка>), так и передать дату в виде строки при создании объекта с помощью new Date(<строка>).',
        question_id: 35,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 36
      {
        title: 'PerformancePaintTiming',
        question_id: 36,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'NavigatorStorage',
        question_id: 36,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'XMLHttpRequest',
        question_id: 36,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 37
      {
        title: 'Ограничений по количеству элементов и их типу нет. +',
        question_id: 37,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Количество элементов не более 2 -1, тип элементов – любой.',
        question_id: 37,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Количество элементов не более 2 -1, тип элементов – кроме объектов.',
        question_id: 37,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Количество элементов любое, тип элементов – кроме массивов.',
        question_id: 37,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 38
      {
        title: 'По номеру символа, с помощью метода charAt().',
        question_id: 38,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'По номеру символа, с помощью метода charAt() или квадратных скобок.',
        question_id: 38,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'По номеру символа, с помощью метода indexOf() или квадратных скобок.',
        question_id: 38,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'По номеру символа, с помощью квадратных скобок.',
        question_id: 38,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 39
      {
        title: 'filter( )',
        question_id: 39,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'split( )',
        question_id: 39,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'parseInt( )',
        question_id: 39,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'я пони',
        question_id: 39,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 40
      {
        title: 'Это способность функции - вызывать саму себя',
        question_id: 40,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Это способность функции - запоминать все переменные',
        question_id: 40,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Это способность функции - запоминать область видимости, в которой эта функция была объявлена',
        question_id: 40,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'что за JavaScript?',
        question_id: 40,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 41
      {
        title: 'var obj = []',
        question_id: 41,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var obj = new {}',
        question_id: 41,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var obj = new Object()',
        question_id: 41,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'var obj = {}',
        question_id: 41,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 42
      {
        title: 'Секунды',
        question_id: 42,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Микросекунды',
        question_id: 42,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Миллисекунды',
        question_id: 42,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Месяцы',
        question_id: 42,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 43
      {
        title: 'Что-то на программистском.',
        question_id: 43,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Это механизм в JavaScript, в котором переменные и объявления функций передвигаются вверх своей области видимости перед тем, как код будет выполнен',
        question_id: 43,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Это объект, который хранит все переменные и функции',
        question_id: 43,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Это услуга по предоставлению ресурсов для размещения информации на сервере, постоянно находящемся в сети',
        question_id: 43,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 44
      {
        title: 'NaN',
        question_id: 44,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'undefined +',
        question_id: 44,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '""',
        question_id: 44,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'null',
        question_id: 44,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // 45
      {
        title: 'keyup',
        question_id: 45,
        isCorrect: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'contextmenu',
        question_id: 45,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'mousescroll',
        question_id: 45,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'mouseenter',
        question_id: 45,
        isCorrect: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Answers', null, {});
  },
};
